Кумбрасьев Марк. Задача 1. Подсчет числа несовпадающих символов двух строк.
allnes/pp_2020_autumn_informatics pull request #105
Opened 2020-11-01 20:34 UTC by Leroyku

2020-11-07 00:39 UTC, allnes requested changes

2020-11-07 00:39 UTC, allnes commented on modules/task_1/kumbrasev_m_diff_char_counter/main.cpp
> +TEST(Parallel_Operations_MPI, empty_strings) {
количество тестов не соотвесвует инструкции

2020-11-07 13:27 UTC, Leroyku commented on modules/task_1/kumbrasev_m_diff_char_counter/main.cpp
> +TEST(Parallel_Operations_MPI, empty_strings) {
добавил еще один

2020-11-13 22:18 UTC, allnes approved these changes

2020-11-13 22:18 UTC, merged