Панова Ольга. Задача 1. Нахождение наиболее отличающихся по значению соседних элементов вектора.
allnes/pp_2020_autumn_informatics pull request #46
Opened 2020-10-26 09:07 UTC by OlgaMakesThings

2020-10-30 10:08 UTC, allnes requested changes

2020-10-30 10:08 UTC, allnes commented on modules/task_1/panova_o_max_difference/max_difference.cpp
> +    MPI_Bcast(v, vec_size, MPI_INT, 0, MPI_COMM_WORLD);  //
для вашей задачи следует вектор разделить на части, рассылка всего вектора всем процессам может вызвать проблемы с памятью

2020-10-31 07:38 UTC, OlgaMakesThings commented
Извините, а можно уточнить, если теоретически я не успею исправить
программу до дедлайна, она не будет зачтена до тех пор, пока не исправлю
или будет, но с низкой оценкой?

пт, 30 окт. 2020 г., 1:08 PM Nesterov Alexander <notifications@github.com>:

> *@allnes* requested changes on this pull request.
> ------------------------------
>
> In modules/task_1/panova_o_max_difference/max_difference.cpp
> <https://github.com/allnes/pp_2020_autumn_informatics/pull/46#discussion_r514990161>
> :
>
> > +          max = v1[i];
>
> +          num = i;
>
> +       }
>
> +    }
>
> +    return num;
>
> +}
>
> +int GetParallelDifference(std::vector<int> vec, int vec_size) {
>
> +    int p_size, p_rank;
>
> +    MPI_Comm_size(MPI_COMM_WORLD, &p_size);
>
> +    MPI_Comm_rank(MPI_COMM_WORLD, &p_rank);
>
> +    int* v = new int[vec_size];
>
> +    int* v1 = new int[vec_size];
>
> +    if (p_rank == 0) {
>
> +       for (int i = 0; i < vec_size; i++) v[i] = vec[i];
>
> +    }
>
> +    MPI_Bcast(v, vec_size, MPI_INT, 0, MPI_COMM_WORLD);  //
>
>
> для вашей задачи следует вектор разделить на части, рассылка всего вектора
> всем процессам может вызвать проблемы с памятью
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/allnes/pp_2020_autumn_informatics/pull/46#pullrequestreview-520527190>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ANMRX27NODK32X2CHGWOSKTSNKGCZANCNFSM4S7DB2QA>
> .
>

2020-10-31 14:49 UTC, allnes approved these changes

2020-10-31 14:49 UTC, merged