Бакаева Мария. Задача 1. Число несовпадающих символов двух строк
allnes/pp_2020_autumn_informatics pull request #68
Opened 2020-10-30 09:33 UTC by bakaevam

2020-10-30 23:23 UTC, allnes requested changes

2020-10-30 23:23 UTC, allnes commented on modules/task_1/bakaeva_m_unmatched_signs/main.cpp
> +TEST(UnmatchedSigns, differenceAtTheEnd) {
количество тестов не соотвествует инструкции

2020-10-31 08:36 UTC, bakaevam commented
@allnes  исправлено

2020-10-31 11:15 UTC, allnes approved these changes

2020-10-31 11:15 UTC, merged